/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "txdgwfqkvtxjndycjqgk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZGd3ZnFrdnR4am5keWNqcWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTMxOTMsImV4cCI6MjA4MjM4OTE5M30.Y5e4YCk5c6-iXLpy0r599JYS0yEI-NlFfyfoo7zNUU0"